backend/models/Role.php
<?php

namespace backend\models;

/**
 * This is the model class for table "my_role".
 *
 * @property string $id 用户角色表
 * @property string $name 角色名
 * @property string $description 角色描述
 * @property string $permission 权限
 * @property int $create_time 创建时间
 */
class Role extends Base
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'my_role';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['create_time'], 'integer'],
            [['name'], 'string', 'max' => 50],
            [['description'], 'string', 'max' => 100],
            [['permission'], 'string', 'max' => 500],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '角色名',
            'description' => '描述',
            'permission' => '权限',
            'create_time' => '创建时间',
        ];
    }

    public function create($data)
    {
        $this->name = $data['name'];
        $this->description = $data['description'];
        $this->permission = json_encode($data['ids']);
        $this->create_time = time();
        if (!$this->save()) {
            $error = array_values($this->getFirstErrors())[0];
            return $this->arrData(100, $error);
        }
        return $this->arrData(200, '添加成功');
    }

    public function edit($data)
    {
        $model = self::findOne($data['id']);
        $model->name = $data['name'];
        $model->description = $data['description'];
        $model->permission = json_encode($data['ids']);
        $model->create_time = time();
        if (!$model->save()) {
            $error = array_values($model->getFirstErrors())[0];
            return $this->arrData(100, $error);
        }
        return $this->arrData(200, '更新成功');
    }


}

backend/controllers/RoleController.php
<?php
/**
 * @author Zeyen
 * @date 2021-05-25
 */
namespace backend\controllers;

use backend\models\Role;
use backend\models\Submenu;
use backend\models\User;
use Yii;
use yii\data\Pagination;

class RoleController extends BaseController
{
    public function actionIndex()
    {
        $query = Role::find();
        $search = Yii::$app->request->get('search');
        $query = $this->condition($query, $search);
        $pagination = new Pagination([
            'totalCount' => $query->count(),
            'defaultPageSize' => 10,
        ]);
        $models = $query
            ->orderBy('id desc')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();
        return $this->render('index', compact('models', 'pagination', 'search'));
    }

    public function condition($query, $search)
    {
        if (isset($search['name']) && $search['name']) {
            $query = $query->andWhere(['like', 'name', $search['name']]);
        }
        if (isset($search['b_time']) && $search['b_time']) {
            $bTime = strtotime($search['b_time'] . ' 00:00:00');
            $query = $query->andWhere(['>=', 'create_time', $bTime]);
        }
        if (isset($search['e_time']) && $search['e_time']) {
            $eTime = strtotime($search['e_time'] . ' 23:59:59');
            $query = $query->andWhere(['<=', 'create_time', $eTime]);
        }
        return $query;
    }

    public function actionCreate()
    {
        $submenus = Submenu::find()->joinWith('route')
            ->where(['is_show' => 1])->orderBy('sort desc')
            ->asArray()->all();
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            if (!isset($post['ids'])) {
                return $this->json(100, '拥有权限不能为空');
            }
            $post['ids'] = array_values($post['ids']);
            foreach ($post['ids'] as &$val) {
                $val = (int)$val;
            }
            $model = new Role();
            $res = $model->create($post);
            if ($res['status'] != 200) {
                return $this->json(100, $res['msg']);
            }
            return $this->json(200, $res['msg']);
        }
        return $this->render('create', compact('submenus'));
    }

    public function actionUpdate()
    {
        $id = (int)Yii::$app->request->get('id');
        $role = Role::findOne($id);
        $submenus = Submenu::find()->joinWith('route')
            ->where(['is_show' => 1])->orderBy('sort desc, id desc')
            ->asArray()->all();
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            if (!isset($post['ids'])) {
                return $this->json(100, '拥有权限不能为空');
            }
            $post['ids'] = array_values($post['ids']);
            foreach ($post['ids'] as &$val) {
                $val = (int)$val;
            }
            $model = new Role();
            $res = $model->edit($post);
            if ($res['status'] != 200) {
                return $this->json(100, $res['msg']);
            }
            return $this->json(200, $res['msg']);
        }
        return $this->render('update', compact('submenus', 'role'));
    }

    public function actionDel()
    {
        $id = (int)Yii::$app->request->get('id');
        if ($id == 1) {
            return $this->json(100, '超级管理员不能删除');
        }
        $user = User::findOne(Yii::$app->user->getId());
        if ($id == $user->role_id) {
            return $this->json(100, '不能删除自身所属的角色');
        }
        $model = User::findOne(['role_id' => $id]);
        if ($model) {
            return $this->json(100, '该角色下含有用户，不能删除');
        }
        $model = Role::findOne($id);
        $res = $model->delete();
        if (!$res) {
            return $this->json(100, '删除失败');
        }
        return $this->json(200, '删除成功');
    }

    public function actionBatchDel()
    {
        $idArr = Yii::$app->request->get('idArr');
        if (in_array(1, $idArr)) {
            return $this->json(100, '超级管理员不能删除');
        }
        $user = User::findOne(Yii::$app->user->getId());
        if (in_array($user->role_id, $idArr)) {
            return $this->json(100, '不能删除自身所属的角色');
        }
        foreach ($idArr as $id) {
            $model = User::findOne(['role_id' => $id]);
            if ($model) {
                return $this->json(100, '该角色下含有用户，不能删除');
            }
        }
        $res = Role::deleteAll(['in', 'id', $idArr]);
        if (!$res) {
            return $this->json(100, '批量删除失败');
        }
        return $this->json(200, '批量删除成功');
    }

}

backend/views/role/create.php
<?php
use yii\helpers\Url;
?>
<div class="x-body">
    <form action="" method="post" class="layui-form layui-form-pane">
        <div class="layui-form-item">
            <label for="name" class="layui-form-label">
                <span class="x-red">*</span>角色名
            </label>
            <div class="layui-input-inline">
                <input type="text" id="name" name="name" required="" lay-verify="required"
                       autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item layui-form-text">
            <label for="description" class="layui-form-label">
                描述
            </label>
            <div class="layui-input-block">
                <textarea placeholder="请输入内容" id="description" name="description" class="layui-textarea" style="min-height: 50px"></textarea>
            </div>
        </div>
        <div class="layui-form-item layui-form-text">
            <label class="layui-form-label">
                拥有权限
            </label>
            <table  class="layui-table layui-input-block">
                <tbody>
                <?php foreach ($submenus as $list): ?>
                <tr>
                    <td style="width: 180px" class="submenu_name">
                        <input type="checkbox" name="submenu_name[]" lay-skin="primary" title="<?= $list['route_name'] ?>">
                    </td>
                    <td>
                        <div class="layui-input-block">
                            <?php foreach ($list['route'] as $item): ?>
                            <input name="ids[]" lay-skin="primary" type="checkbox" value="<?= $item['id'] ?>" title="<?= $item['route_name'] ?>">
                            <?php endforeach; ?>
                        </div>
                    </td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="layui-form-item">
            <button class="layui-btn" lay-submit="" lay-filter="add">增加</button>
        </div>
    </form>
</div>

<?php $this->beginBlock('footer') ?>
<script>
    layui.use(['form','layer'], function(){
        $ = layui.jquery;
        var form = layui.form, layer = layui.layer;

        $('.submenu_name').click(function () {
            if ($(this).find('input').prop('checked')) {
                $(this).next().find('.layui-input-block').find('input').attr('checked', 'checked');
            } else {
                $(this).next().find('.layui-input-block').find('input').removeAttr('checked');
            }
            form.render("checkbox")
        });

        //监听提交
        form.on('submit(add)', function(data){
            layer.load(3);
            $.post('<?= Url::to(['role/create']) ?>', data.field, function (res) {
                layer.closeAll();
                if (res.status === 200) {
                    layer.msg(res.msg, {icon: 1,time: 1500}, function () {
                        var index = parent.layer.getFrameIndex(window.name);
                        parent.layer.close(index);
                        parent.location.reload();
                    })
                } else {
                    layer.msg(res.msg, {icon: 2, time: 1500})
                }
            }, 'json');
            return false;
        });
    });
</script>
<?php $this->endBlock() ?>

backend/views/role/index.php
<?php
use yii\helpers\Url;
?>

<div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="javascript:;">首页</a>
        <a href="javascript:;">管理员管理</a>
        <a href="javascript:;"><cite>管理员列表</cite></a>
      </span>
    <a class="layui-btn layui-btn-small refresh-btn" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:38px">ဂ</i></a>
</div>
<div class="x-body">
    <div class="layui-row">
        <form class="layui-form layui-col-md12 x-so">
            <input type="text" name="search[name]"  placeholder="角色名" autocomplete="off" class="layui-input"
                   value="<?= isset($search['name']) ? $search['name'] : '' ?>">
            <input class="layui-input" placeholder="开始日" name="search[b_time]" id="start"
                   value="<?= isset($search['b_time']) ? $search['b_time'] : '' ?>" autocomplete="off">
            <input class="layui-input" placeholder="截止日" name="search[e_time]" id="end"
                   value="<?= isset($search['e_time']) ? $search['e_time'] : '' ?>" autocomplete="off">
            <button class="layui-btn" type="submit"><i class="layui-icon">&#xe615;</i></button>
            <button class="layui-btn" type="button" onclick="location.href= '<?= Url::to([$this->context->id . '/index'])?>'" >
                <i class="layui-icon">&#xe666;</i>
            </button>
        </form>
    </div>
    <xblock>
        <button class="layui-btn layui-btn-danger" onclick="batch_del('<?= Url::to(['role/batch-del']) ?>')"><i class="layui-icon"></i>批量删除</button>
        <button class="layui-btn" onclick="x_admin_show('添加','<?=  Url::to(['role/create']) ?>')"><i class="layui-icon"></i>添加</button>
        <span class="x-right" style="line-height:40px">共有数据：<span class="count_num"><?= $pagination->totalCount ?></span> 条 ( <?= $pagination->getPageCount() ?> 页 )</span>
    </xblock>
    <table class="layui-table">
        <thead>
        <tr>
            <th>
                <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i class="layui-icon">&#xe605;</i></div>
            </th>
            <th>ID</th>
            <th>角色名</th>
            <th>描述</th>
            <th>操作</th>
        </thead>
        <tbody>
        <?php foreach ($models as $list): ?>
        <tr>
            <td>
                <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='<?= $list['id']?>'><i class="layui-icon">&#xe605;</i></div>
            </td>
            <td><?= $list['id'] ?></td>
            <td><?= $list['name'] ?></td>
            <td><?= $list['description'] ?></td>
            <td class="td-manage">
                <a title="编辑"  onclick="x_admin_show('编辑','<?= Url::to(['role/update', 'id' => $list['id']]) ?>')" href="javascript:;">
                    <i class="layui-icon">&#xe642;</i>
                </a>
                <a title="删除" onclick="del(this, '<?= $list['id'] ?>', '<?= Url::to(['role/del']) ?>')" href="javascript:;">
                    <i class="layui-icon">&#xe640;</i>
                </a>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php if (empty($models)): ?>
        <p class="text-empty">-- 暂无数据 --</p>
    <?php endif; ?>

    <?= $this->render('@app/views/layouts/pagination', compact('pagination')) ?>

</div>

backend/views/role/update.php
<?php
use yii\helpers\Url;
?>
<div class="x-body">
    <form action="" method="post" class="layui-form layui-form-pane">
        <div class="layui-form-item">
            <label for="name" class="layui-form-label">
                <span class="x-red">*</span>角色名
            </label>
            <div class="layui-input-inline">
                <input type="hidden" name="id" value="<?= $role['id'] ?>">
                <input type="text" id="name" name="name" required="" lay-verify="required"
                       autocomplete="off" class="layui-input" value="<?= $role['name'] ?>">
            </div>
        </div>
        <div class="layui-form-item layui-form-text">
            <label for="description" class="layui-form-label">
                描述
            </label>
            <div class="layui-input-block">
                <textarea placeholder="请输入内容" id="description" name="description" class="layui-textarea" style="min-height: 50px"><?= $role['description'] ?></textarea>
            </div>
        </div>
        <div class="layui-form-item layui-form-text">
            <label class="layui-form-label">
                拥有权限
            </label>
            <table  class="layui-table layui-input-block">
                <tbody>
                <?php foreach ($submenus as $list): ?>
                    <tr>
                        <td style="width: 180px" class="submenu_name">
                            <input type="checkbox" name="submenu_name[]" lay-skin="primary" title="<?= $list['route_name'] ?>">
                        </td>
                        <td>
                            <div class="layui-input-block">
                                <?php foreach ($list['route'] as $item): ?>
                                    <input name="ids[]" lay-skin="primary" type="checkbox" value="<?= $item['id'] ?>" title="<?= $item['route_name'] ?>"
                                    <?= in_array($item['id'], json_decode($role['permission'])) ? 'checked' : '' ?>>
                                <?php endforeach; ?>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="layui-form-item">
            <button class="layui-btn" lay-submit="" lay-filter="update">更新</button>
        </div>
    </form>
</div>

<?php $this->beginBlock('footer') ?>
<script>
    layui.use(['form','layer'], function(){
        $ = layui.jquery;
        var form = layui.form, layer = layui.layer;

        $('.submenu_name').click(function () {
            if ($(this).find('input').prop('checked')) {
                $(this).next().find('.layui-input-block').find('input').attr('checked', 'checked');
            } else {
                $(this).next().find('.layui-input-block').find('input').removeAttr('checked');
            }
            form.render("checkbox")
        });

        //监听提交
        form.on('submit(update)', function(data){
            layer.load(3);
            $.post('<?= Url::to(['role/update']) ?>', data.field, function (res) {
                layer.closeAll();
                if (res.status === 200) {
                    layer.msg(res.msg, {icon: 1,time: 1500}, function () {
                        var index = parent.layer.getFrameIndex(window.name);
                        parent.layer.close(index);
                        parent.location.reload();
                    })
                } else {
                    layer.msg(res.msg, {icon: 2, time: 1500})
                }
            }, 'json');
            return false;
        });

    });
</script>
<?php $this->endBlock() ?>